# https://pytorch.org/tutorials/beginner/basics/transforms_tutorial.html

In [1]:
import torch
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda

ds = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
    target_transform=Lambda(lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y), value=1))
)

In [11]:
t = torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(6), value=1)
print(t)

index = torch.tensor([[0, 1, 2]])
value = 2
new_tensor = torch.zeros(3, 5).scatter_(0, index, value)
print(index)
print(new_tensor)

tensor([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])
tensor([[0, 1, 2]])
tensor([[2., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 2., 0., 0.]])
